### DISCUSSION TITLE
Key/value store

### DISCUSSION THREAD

**Discussion by frenck** [frenck/spook#11] [Ideas]
Random idea, provide a key-value store, that can be used to get/set values for use in... whatever.
In a way, it isn't recorded in the database and preserves its original datatype.

Maybe make a difference between persistent and non-persistent values or something.

No idea.

**Comment by PiotrMachowski** [comment]
There already exists a a custom integration that supports similar use case: [Saver](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver)

**Reply by frenck** [reply]
That is saving entity states, that is not something I meant with the above.

**Reply by PiotrMachowski** [reply]
That was the main goal of said integration, but it also supports variables:
```yaml
service: saver.set_variable
data:
  name: counter
  value: 3
```
```yaml
  - service: input_text.set_value
    data_template:
      entity_id: input_text.counter_description
      value: "Counter has value {{ state_attr('saver.saver', 'variables')['counter'] }}"
```
