### DISCUSSION TITLE
how do i  use Import statistics?

### DISCUSSION THREAD

**Discussion by RDickens** [frenck/spook#19] [Q&A] [answered]
im trying to import historical data from my electricity supplier. Its in a csv format but i cant get the import to work.

can anyone help?

yaml of spook settings
-------------------------
service: recorder.import_statistics
data:
  has_mean: true
  has_sum: false
  statistics_id: input_number.test
  source: elec.csv
  stats: start mean

data example
-------------
2023-02-22T23:30:00.000Z, 0.173
2023-02-23T00:00:00.000Z, 0.137
2023-02-23T00:30:00.000Z, 0.103

**Comment by dbwarrior1975** [comment]
I am also trying figured out how this service call should be done.
I also assume that historical data is imported via csv. This csv is stored under config folder.
Then you create simple service call. 
I had tried few different notations and always got:

2023-05-03 13:02:35.284 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2023-05-03 13:02:35.285 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2023-05-03 13:02:35.287 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: expected a dictionary @ data['stats'][0]
2023-05-03 13:02:35.299 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140435243214512] Error handling message: expected a dictionary @data['stats'][0]. Got None expected a dictionary @ data['stats'][1]. Got None expected a dictionary @ data['stats'][2]. Got None (invalid_format) mikko from 192.168.100.27

**Reply by dbwarrior1975** [reply, marked as answer]
I made some testing and get some progres. First, i find out, that source DON't refer for CSV, then it was pretty straight forward to follow documentation:
Here is my test call and result:
![kuva](https://user-images.githubusercontent.com/80710485/236603438-d51ee577-1e96-491c-80e2-1ae19ead34cc.png)

**Comment by janis-vitols** [comment]
Hello,

Thought about using Energy dashboard in HA, but my provider doesn't have easy API to fetch the data with REST or other integration. Decided for now to enter history data manually. After reading a lot of topics I have found out Spook.

Tried to call this `Import Statistics` as it's shown in docs: https://spook.frenck.dev/recorder but it was throwing error messages. Later found some different examples in some kind of forum topic and now also an example here. Still somehow I can't manage to update statistics 🙈 

Maybe someone can spot the problem which I have here 🙏 

1) I have created custom sensor
```
template:
  - sensor:
      - name: "Manual energy consumption metter"
        unique_id: manual_energy_consumption_metter
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        state: 50.55
        attributes:         
          last_reset: '1970-01-01T00:00:00+00:00'
```

This allows me to use/pick this sensor in Energy configuration.

2) Then I try to update state with Spook like this:
```
service: recorder.import_statistics
data:
  has_mean: false
  has_sum: false
  statistic_id: sensor.manual_energy_consumption_metter
  source: "recorder"
  unit_of_measurement: "kWh"
  stats:
    - start: "2023-11-19T00:00:00+00:00"
      last_reset: "2023-11-01T00:00:00+00:00"
      state: 100
```
<img width="1174" alt="Screenshot 2023-11-19 at 21 10 27" src="https://github.com/frenck/spook/assets/8654229/d166a44e-5081-4932-b103-842f55867cf0">

Icon shows success.
(I have also tried playing around with the mean/sum flags and providing min/max/mean, with different start dates etc).

3) Then I check the History for this sensor, but I don't see my data in graph.
<img width="1169" alt="Screenshot 2023-11-19 at 21 11 55" src="https://github.com/frenck/spook/assets/8654229/e37dd4df-43e7-437f-a993-db9f993b4a9d">
