### DISCUSSION TITLE
Copy from a statistic to another

### DISCUSSION THREAD

**Discussion by miguelangellv** [frenck/spook#397] [Ideas]
Sometimes, you change a sensor for other and want keep the old data.

So, a variant of "import statistics" sensor that  use other sensor as source and inject in new sensor

```yaml
service.statistics_import_from_sensor:
data:
  source: sensor.old_sensor
  target: sensor.new_sensor
  start: 2022-01-01 #Optional
  end: 2023-10-01  #Optional
  
 ```
