### DISCUSSION TITLE
Spook Zone Update - GPS of Device for RV/Trailer

### DISCUSSION THREAD

**Discussion by pmulkins** [frenck/spook#453] [Q&A] [answered]
Hello!

Thank you for this integration, it should be helpful for what I am looking to achieve. Unfortunately, it is _currently_ beyond my abilities. My use case is I have an RV that I would like to dynamically set my zone based on my travels, and setup automations ( ie. based on my distance from my zone (=home=rv)). I have a tablet (as the interface of HA), with cellular connectivity on all the time, reporting its GPS location to HA. How can I use the GPS data from the tablet and update the Zone GPS coordinates in the Spooky zone.update service?

Any help would be greatly appreciated!

**Comment by martinhoess** [comment, marked as answer]
Do you mean something like this?

```
service: zone.update
data:
  entity_id: zone.test
  latitude: "{{ state_attr('device_tracker.iphone', 'latitude') }}"
  longitude: "{{ state_attr('device_tracker.iphone', 'longitude') }}"
```

![image](https://github.com/frenck/spook/assets/47973549/c2cfe04f-f4f1-4fa6-807e-43ea4af2b4e1)
