### DISCUSSION TITLE
Unable to use service homeassistant.disable_devices with multiple devices in automation

### DISCUSSION THREAD

**Discussion by bdf0506** [frenck/spook#527] [Q&A]
I have an automation that uses the following service call:

````
service: homeassistant.disable_device
data:
  device_id: 
    - 0d405f81f0bedd5af78c82bfd86e240a
    - 93bd3701e7e098b8b1de58d94acbf2bc
    - fea58004c098d742079b421c3d674aab
    - aad6033acabdea5f75f19af03311ed6d
````

While this service call works fine in YAML, it does NOT work in the visual editor. As a result, if you make the automation like this, and save it, once you go back into the automation, things are not pretty and data is lost.

````
description: ""
mode: single
trigger: []
condition: []
action:
  - service: homeassistant.disable_device
    data:
      device_id:
        - 0d405f81f0bedd5af78c82bfd86e240a
        - 93bd3701e7e098b8b1de58d94acbf2bc
        - fea58004c098d742079b421c3d674aab
        - aad6033acabdea5f75f19af03311ed6d
````

Then you save it and go back in, and only the first device_id is retained.

````
alias: test automation
description: ""
trigger: []
condition: []
action:
  - service: homeassistant.disable_device
    data:
      device_id: 0d405f81f0bedd5af78c82bfd86e240a
mode: single
````

This likely has something to do with the fact that you can't call multiple devices in the visual editor and you can only do this with YAML.
