### DISCUSSION TITLE
What is disabling a device suppose to do ?

### DISCUSSION THREAD

**Discussion by jerry34ha** [frenck/spook#664] [Q&A]
Hi,
I'm switching off my internet connexion and wifi at night to save energy.

I use the multiscrape custom component to scrape the wait time until the next bus every minute. Due to the lack of connectivity, HA logs are filled up with scrape errors every minute.
I want to keep the logs clean (and save my HA Green onboard storage...).

I installed Spook to homeassistant.disable_device multiscrape and disable_entity mysensor 

This does not stop the multiscrape custom component from trying to refresh the entity, hence the logs are still full of errors.

The Overkiz integration also throws some errors at night so I used homeassistant.disable_integration but again that does not make errors go away at night.

Am I wrong to assume that disabling the multiscrape device would prevent HA from refreshing the associated sensors ?
Am I wrong to assume that disabling the Overkiz integration would stop it from attempting to refresh the associated devices/entities ?

Thank you

(HA core 2024.2.5 on HA Green)

**Comment by frenck** [comment]
> This does not stop the multiscrape custom component from trying to refresh the entity

That is possible, the scape probably happens on config entry / integration level, and not device.

> Am I wrong to assume that disabling the multiscrape device would prevent HA from refreshing the associated sensors ?

Depends on the case / integration. But to me it sounds like you are looking for disabling an integration (not a device).

../Frenck

**Reply by jerry34ha** [reply]
Thank you for your response (and thank you for Spook!).

I can see a "Multiscrape" entry in the dropdown of home assistant.disable_device but not in the disable_integration dropdown.

I seems that all the stuff downloaded from HACS appears in the disable_device dropdown, including integrations (and custom cards and themes...).

So I used the great spook doc to get the config_entry_id of Multiscrape and edited my automation in YAML.
Will tell you tomorrow if it worked.

**Reply by frenck** [reply]
>  but not in the disable_integration dropdown

Correct, as you won't disable an integration, but an instance of an integration; which is known as a config entry. So, look for `disable_config_entry`.

../Frenck

**Reply by jerry34ha** [reply]
Well, this did not work (scraping continued):
```
alias: Désactiver Scrape
description: >-
  Désactiver les entité Scrape la nuit car je coupe le wifi et ça évite de
  remplir le log d'erreurs
trigger:
  - platform: time
    at: "21:55:00"
condition: []
action:
  - service: homeassistant.disable_config_entry
    metadata: {}
    data:
      config_entry_id:
        - d6ad69489a018ea5ab0c6084f6b48b6b
mode: single
```
I will try with the Overkiz integration to see if the issue is with Multiscrape.
