### DISCUSSION TITLE
group.set service for new style groups

### DISCUSSION THREAD

**Discussion by dinki** [frenck/spook#709] [Ideas]
Hey there.  Thanks for the cool integration.  I am in need to be able to add/remove members from a new style (aka from the interface) media player group.  I know it is possible to use the [group.set service](https://www.home-assistant.io/integrations/group#services) for the old style groups but it does not appear that similar functionality exists for the new style groups.  Would it be possible to extend Spook to be able to modify these group members?

My use case is that I have a group of media player entities in a media player group that I uses Google TTS to broadcast messages to.  I am wanting to implement a do not disturb (DND) mode that would allow for that entity to be removed from the group whenever it's DND attribute is changed to true via automation.  The broadcast message would then not be played on those devices in DND mode.  At current, I cannot think of a way to get this done without a bunch of templating and even that I'm not sure will work as I'd like the message to be broadcast simultaneously.

Any ideas?

**Comment by TheFes** [comment]
I've seens your question on the HA Discord about this.
2024.4 will introduce labels, and Frenck mentioned he would add service calls to add and remove labels. So instead of groups, you could also use labels.

BTW you could also use old school groups, but instead of targeting the group itself, you can target the group members by using the `entity_id` attribute.

**Reply by dinki** [reply]
> I've seens your question on the HA Discord about this.
2024.4 will introduce labels, and Frenck mentioned he would add service calls to add and remove labels. So instead of groups, you could also use labels.

Oh great.  That would definitely work.  Thanks for the heads up.

> BTW you could also use old school groups, but instead of targeting the group itself, you can target the group members by using the entity_id attribute.

I don't understand what you mean by this.

**Comment by TheFes** [comment]
> I don't understand what you mean by this.

So you have a group entity which has all the media_players you do want to send the message to, eg `group.send_tts`

While you can't target that group itself in a tts service call, as it isn't a media player entity, you can target the group members

eg

```yaml
service: tts.cloud_say
target:
  entity_id: "{{ state_attr('group.send_tts', 'entity_id') | list }}"
data:
  message: This is a nice message
```

or, using the new tts entity
```yaml
repeat:
  for_each: "{{ state_attr('group.send_tts', 'entity_id') | list }}"
  sequence:
    - service: tts.speak
      data:
        media_player_entity_id: "{{ repeat.item }}"
        message: Another nice message
      target:
        entity_id: tts.home_assistant_cloud
```

**Reply by dinki** [reply]
```
service: chime_tts.say
target:
  entity_id: >-
    {{ (expand('group.assist_satellites') |
    selectattr('attributes.do_not_disturb', 'eq','false') |
    map(attribute='attributes.mediaplayer_device') | list) }}
data:
  chime_path: www/viewassist/broadcast.mp3
  tts_playback_speed: 100
  volume_level: 1
  message: "{{ state_attr(target_satellite_device, 'message') }}"
  tts_platform: google_translate
```

Ah yes.  That is what I settled on yesterday.  I am trying to write this as simply as possible as I have this grand dream of sharing this information with others so they can use this too.  I think there is interest in my project but maybe it will only be adopted by a few brave souls.  Nevertheless, I'm trying to reduce the complexity and document what I'm doing so others can find better ways to use it and improve it.

Thanks again for your help.  I'll close this one.
