### DISCUSSION TITLE
Using create/delete zone in dynamic setup for gas stations

### DISCUSSION THREAD

**Discussion by vingerha** [frenck/spook#819] [Show and tell]
I am using an integration that provides the gas stations in a self-defined radius around a sensor (could be devide tracker or zone)
The service/action provides these as a list, each entry having its own lat/lon
By using automation 'for each), one can read the list and pass-on the data to zone.create and (if a moving device is used) zone.delete
The result can then be displayed in a map card

So why is this special? Other solutions would require the integration to create sensors with a lat/lon and make that dynamic based on the location of the person/device around which to search, that is a lot (!) more complex

```
alias: Gas stations around me
description: ""
trigger:
  - platform: time_pattern
    minutes: /5
condition: []
action:
  - repeat:
      for_each: >-
        {{states.zone |selectattr('entity_id', 'search',
        'station_')|map(attribute='entity_id') | list }}
      sequence:
        - action: zone.delete
          data:
            entity_id: "{{ repeat.item }}"
  - repeat:
      for_each: "{{ state_attr('sensor.test_stations', 'stations') | list  }}"
      sequence:
        - action: zone.create
          data:
            radius: 100
            icon: mdi:gas-station-in-use-outline
            name: "{{ 'station_' + repeat.item.name }}"
            latitude: "{{ repeat.item.latitude }}"
            longitude: "{{ repeat.item.longitude }}"
mode: single
```

![image](https://github.com/user-attachments/assets/e3fe1ecf-a04b-40c7-8f33-bfab8b0705f9)
