### DISCUSSION TITLE
False detections - how to troubleshoot (or is it a bug?)

### DISCUSSION THREAD

**Discussion by mwareman** [frenck/spook#861] [Q&A]
I changed my Android phone, and it's triggered Spook to report a bunch of things (when I removed the old one). Most are valid. However, some are....  odd..

For example:

```
The automation "Dusk2Dawn-Dawn" (automation.dusk2dawn_dawn) has an unknown action: notify.mobile_app_pixel_6_pro_michael.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.
```

Fine. I had deleted the Pixel 6 Pro (mobile_app_pixel_6_pro_michael) and it's now a Pixel 9 Pro (mobile_app_pixel_9_pro_michael). So - I hit up editing the automation and....

```
alias: Dusk2Dawn-Dawn
description: ""
triggers:
  - entity_id: sun.sun
    attribute: elevation
    above: -4
    trigger: numeric_state
conditions: []
actions:
  - data:
      title: Dusk2Dawn
      message: Dawn
    action: notify.mobile_app_pixel_9_pro
mode: single
```

It's already using the newer (and correct) notify service identity.

What's going on? Not sure where to begin here...  but I have about 30 'fixes' in Spook that are experiancing this issue. The fix is indicating my old phone is still in the automation, but when I go to edit the automation I've already changed it.
