### DISCUSSION TITLE
Expose Spook individual repairs as entities

### DISCUSSION THREAD

**Discussion by drueppela** [frenck/spook#883] [Ideas]
Expose Spook individual repairs as entities would make it possible to show individual spook repairs as single tile card via Auto-entities

Analogous to

```yaml
type: custom:auto-entities
card:
  type: grid
  columns: 1
  square: false
card_param: cards
filter:
  template: |-
    {% for x in states.light -%}
      {%- if x.state == 'on' -%}
        {{
          {
            'type': 'tile',
            'entity': x.entity_id,
            'tap_action': {
              'action': 'toggle'
            }
          }
        }},
      {%- endif -%}
    {%- endfor %}
```
