### DISCUSSION TITLE
Help needed: How to pass device_id via template to add_label_to_device?

### DISCUSSION THREAD

**Discussion by nicknol** [frenck/spook#934] [Q&A]
I want to add a label (e.g. `ignore_status`) automatically to a device as soon as it is put into the area "`stock`", means it is not used at the moment but already configured.
I already have a small automation to detect the area change and to get the device_id via `trigger.event.data.device_id`, and now I want to use `add_label_to_device` to add the label ignore_status to the detected device_id `trigger.event.data.device_id`. 
But it seems that I can't pass the device_id `trigger.event.data.device_id` using template syntax.

How could I pass `trigger.event.data.device_id` to the call to ` pass device_id via template`?

**Comment by nicknol** [comment]
found it

```
actions:
  - action: homeassistant.add_label_to_device
    metadata: {}
    data:
      label_id: ignore_status
      device_id: "{{ trigger.event.data.device_id }}"
```
