### ISSUE TITLE
AttributeError: 'Template' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Mariusthvdb** [frenck/spook#17]
error in the HA log:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.spook
Source: custom_components/spook/repairs/script_unknown_entity_references.py:96 
Integration: Spook (documentation, issues) 
First occurred: 15:37:18 (66 occurrences) 
Last logged: 16:07:46

Unexpected exception from <bound method SpookRepair.async_inspect of <custom_components.spook.repairs.script_unknown_entity_references.SpookRepair object at 0x7f6202b55990>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 109, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs/script_unknown_entity_references.py", line 92, in async_inspect
    referenced_entities = {
  File "/config/custom_components/spook/repairs/script_unknown_entity_references.py", line 96, in <setcomp>
    not entity_id.startswith("device_tracker.")
AttributeError: 'Template' object has no attribute 'startswith'
```

v 10.111

**Comment by frenck** [comment]
This is actually interesting, as the codebase from HA doesn't expect that to happen.

This means that the typing in HA is incorrect, but also that the handling in Core itself is incomplete. So, this is nice. We can contribute findings back this way.

I have an idea of how to approach/solve this in Spook itself, if that works as expected, I can go in and improve Core for this (but needs a bit of work).

../Frenck

**Comment by frenck** [comment]
Could you provide a way to reproduce it for me? Could you provide an example automation/script? I'm failing at reproducing this.

At first glance, it makes sense it fails... but looking deeper, it starts to look odd.

**Comment by Mariusthvdb** [comment]
tbh, I wouldn't know how...
since it mentions device_tracker, Ive checked my automations and scripts using that, but there is no obvious contender. 

unless Spook sees things like:
```
  epson_printer:
    alias: Epson printer
    mode: restart
    sequence:
      - wait_template: >
          {{is_state('device_tracker.printer_epson','home')}}
      - delay: 5
      - service: script.update_epson_cartridge_sensors
```

and notices the device is not powered, so 'not_home'. but that would be regular use of a device_tracker, so no use to alert.
ofc, there are many such automations/scripts, no idea where to start disabling to see what might be the trigger for Spook.

maybe an extra line with the trigger for the error can be added?

unless `object at 0x7faa9dac0430` would already be that. In that case I need some help finding that that would be. I ran a search for it in the  full config but it was not found

what to think of this though:

<img width="942" alt="Scherm­afbeelding 2023-03-02 om 10 43 15" src="https://user-images.githubusercontent.com/33354141/222391628-c57ed7cd-d223-4190-82a7-0cb534e37f86.png">

**Comment by Mariusthvdb** [comment]
o wow, I had a brain block...... ofc, I should have been alarmed by the 'starts with'....

I have made this new device alerter
```
  - alias: New device registered config
    id: new_device_registered_config
    mode: queued
    trigger:
      platform: event
      event_type: entity_registry_updated
      event_data:
        action: create
    condition: >
      {{trigger.event.data.entity_id.startswith('device_tracker')}}
    action:
      - variables:
          data: >
            {{trigger.event.data}}
          entity: >
            {{trigger.event.data.entity_id}}
          name: >
            {{state_attr(entity,'friendly_name')}}
          host: >
            {{state_attr(entity,'host_name')}}
          ip: >
            {{state_attr(entity,'ip')}}
          mac: >
            {{state_attr(entity,'mac')}}
          source: >
            {{state_attr(entity,'source_type')}}
          id: >
            {{device_id(entity)}}
          config: >
            - entity: {{entity}},

            - name: {{name}},

            - host: {{host}},

            - ip: {{ip}},

            - mac: {{mac}},

            - source_type: {{source_type}}

            - id: {{id}}
          time: >
            {{now().timestamp()|timestamp_custom('%X')}}
          title: >
            {{time}} - New device registered: {{name}}
          message_body: >
           New device config: {{config}}

      - service: system_log.write
        data:
          message: >
            {{data}}
          level: warning
          logger: homeassistant.components.device_tracker
      - choose:
          - alias: 'Write new device to log?'
            conditions:
              condition: state
              entity_id: input_boolean.write_new_device_to_log
              state: 'on'
            sequence:
              service: system_log.write
              data:
                message: >
                  {{message_body}}
                  Event: {{trigger.event}}
                  Data: {{data}}
                  Data verbose: {{trigger.event.data}}
                level: warning
                logger: homeassistant.components.device_tracker
      - choose:
          - alias: 'Create persistent notification for new device?'
            conditions:
              condition: state
              entity_id: input_boolean.persistent_notification_new_device
              state: 'on'
            sequence:
              service: persistent_notification.create
              data:
                title: >
                  {{title}}
                message: >
                  {{message_body}}
      - choose:
          - alias: 'Notify of new device?'
            conditions:
              condition: state
              entity_id: input_boolean.notify_new_device
              state: 'on'
            sequence:
              service: notify.mobile_app_marijn
              data:
                title: >
                  {{title}}
                message: >
                  {{message_body}}
```

**Comment by frenck** [comment]
I'm not able to reproduce it with the examples given, nor do I see a possible code path that may cause this (not in Spook and not in HA).

This is the output from the first bigger example you have in the last response:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/195327/222823737-76717402-bcc0-419c-9f37-a06254980b48.png">

I have tested this on both my prod & dev setups, and both had the same results.

../Frenck

**Comment by Mariusthvdb** [comment]
yeah, but that is a real 'repair'... I only get the errors in the logs.

I now realize the whole line is created by the `script_unknown_entity_references.py` itself, where above, I figured the device_tracker mentioning is because of a real missing device_tracker..

how can it error like that, while it should me silent about it in the first place? 
 

> Filter out scenes, groups & device_tracker entities.


Ive scrutinized my complete yaml config for device_trackers, and did find 2 being mentioned that are not available in the states. 1 is inside a group:

```
group:

  device_trackers_media:
    name: Device trackers media
    icon: mdi:theater
    entities:

      - device_tracker.nintendo_switch
```

and 1 is inside  a binary:

```
template:

  - binary_sensor:

      - unique_id: imac_louise_off
        name: iMac Louise Off
        state: >
          {{is_state('device_tracker.imac_lan','not_home') and
            is_state('device_tracker.imac_wifi','not_home')}}
        delay_on:
          seconds: 30
```

the _wifi one not existing currently in the states.

I will. comment those and restart, maybe that will fix it. 

then again, shouldnt this be recognized by Spook, and brought up as 2 repairs?
