### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by holdestmade** [frenck/spook#192]
Sorry Frenck, another one, getting this on v0.13.131315. This one repeats

Logger: custom_components.spook
Source: custom_components/spook/repairs/lovelace_unknown_entity_references.py:254
Integration: Spook (documentation, issues)
First occurred: 09:29:35 (5 occurrences)
Last logged: 09:30:34

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff4c76dbd0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 117, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs/__init__.py", line 130, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 108, in async_inspect
    for entity_id in self.__async_extract_entities(config)
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 159, in __async_extract_entities
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 213, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_actions(config))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 254, in __async_extract_entities_from_actions
    if action := config.get(key):
AttributeError: 'list' object has no attribute 'get'

**Comment by frenck** [comment]
Don't be sorry! It really helps!

There are so many cards and stuff out, that it is impossible for me to pre-think/catch them all. So these reports allow me to iteratively improve it 👍 

../Frenck

**Comment by frenck** [comment]
It looks like you have a YAML list on a key that is either `tap_action:`, `hold_action:`, `double_tap_action:`, or `subtitle_tap_action:`.

How do those look in your configuration?

../Frenck

**Comment by holdestmade** [comment]
Is this what you mean ?

Now I look at it, I can combine them and there is a risk they might go out of sync, I'll adjust

```
            tap_action:
              - action: call-service
                service: homeassistant.toggle
                data:
                  entity_id:
                    - automation.immersion_heater_schedule_off
              - action: call-service
                service: homeassistant.toggle
                data:
                  entity_id:
                    - automation.immersion_heater_schedule_on
```
