### ISSUE TITLE
Spook treats default values in Blueprint template as invalid

### ISSUE THREAD

**Issue by bennydiamond** [frenck/spook#516]
### What version of Spook are you using?

2023.12.4

### What version of Home Assistant are you using?

2023.12.4

### The problem

Spook reports an issue with a blueprint instance.

Message is the following
```
This automation references the following devices, which are unknown to Home Assistant:

    ''
```

"Problematic" blueprint is https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/controllers/ikea_ictc_g_1/ikea_ictc_g_1.yaml

The issue originates from the fact that at least one of the 2 first inputs is going to stay at default value.

```
controller_device:
      name: (deCONZ, ZHA) Controller Device
      description: The controller device to use for the automation. Choose a value only if the remote is integrated with deCONZ, ZHA.
      default: ''
      selector:
        device:
    controller_entity:
      name: (Zigbee2MQTT) Controller Entity
      description: The action sensor of the controller to use for the automation. Choose a value only if the remote is integrated with Zigbee2MQTT.
      default: ''
      selector:
        entity:
          domain: sensor
```

So is this a bug of Spook? I'm not so sure but it would be nice to not get a warning about it since it's intended behavior.
