### ISSUE TITLE
Repair: False positive for missing service "notify.alexa_media"

### ISSUE THREAD

**Issue by Bastian007** [frenck/spook#624]
### What version of Spook are you using?

2.2.2

### What version of Home Assistant are you using?

2024.2.1

### The problem

Spook is showing a Repair for an automation with detected missing service which is available.

_"The automation "xyz" (automation.xyz) has an action that calls an unknown service: **notify.alexa_media**.
This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it._

![image](https://github.com/frenck/spook/assets/12425311/ad023658-41a9-4609-a949-ff0f1048e9b5)

The automation is also up and running.
To give you the full picture I also pasting the automation here:
```
alias: Mailbox - Benachrichtigung Post im Briefkasten
description: >-
  ffmpeg -y -i jingle.mp3 -ac 2 -codec:a libmp3lame -b:a 48k -ar 16000
  jingle_converted.mp3
trigger:
  - type: vibration
    platform: device
    device_id: 75940952796e8e0b5ef92804331d8a47
    entity_id: binary_sensor.aqara_vibration_sensor_briefkasten_vibration
    domain: binary_sensor
condition:
  - condition: time
    before: "19:00:00"
    after: "07:00:00"
  - condition: state
    entity_id: input_boolean.speech_notifications
    state: "on"
  - condition: numeric_state
    entity_id: sensor.gw1100a_max_daily_gust
    below: 25
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    target:
      entity_id:
        - media_player.echo_wohnzimmer
  - service: notify.mobile_app_handy_bastian_s10e
    data:
      message: Du hast Post im Briefkasten
      title: Mailbox
      data:
        actions:
          - action: DONE_MAILBOX
            title: Briefkasten geleert
  - service: notify.alexa_media
    data:
      message: >-
        <audio
        src="https://qrzjfyu8n3ggeslgjhpkgdfb6hp28ka0.ui.nabu.casa/local/mp3/jingle_converted.mp3"
        />
      data:
        type: tts
      target:
        - media_player.echo_wohnzimmer
  - service: notify.alexa_media
    data:
      target:
        - media_player.echo_dachstudio
        - media_player.echo_wohnzimmer
      data:
        type: announce
      message: Hey, Du hast Post im Briefkasten!
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.mail_arrived
  - service: input_datetime.set_datetime
    data:
      timestamp: "{{ now().timestamp() }}"
    target:
      entity_id: input_datetime.mailbox_last_triggered
  - service: media_player.volume_set
    data:
      volume_level: 0.3
    target:
      entity_id:
        - media_player.echo_wohnzimmer
        - media_player.echo_dachstudio
mode: single
```
