### ISSUE TITLE
False positives on missing entities

### ISSUE THREAD

**Issue by avbor** [frenck/spook#67]
Hi!
I have some automations with `persistent_notification.*` entities, like this:
```
- alias: "HASS: Login Failed [notify to group system]"
  id: 142e502b-3e63-49e3-b790-9150f155dc6d
  mode: queued
  max: 5
  trigger:
    - platform: state
      entity_id: persistent_notification.http_login
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != off }}"
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tlg_group_system
        disable_web_page_preview: true
        message: |
          *Внимание!*
          Неудачная попытка входа, ошибка авторизации!
          Источник: {{ state_attr('persistent_notification.http_login','message') | regex_findall_index('from (.*)\. ') }}
          _http://whatismyipaddress.com/ip/{{ state_attr('persistent_notification.http_login','message') | regex_findall_index('\((.*)\)') }}_
    - service: persistent_notification.dismiss
      data:
        notification_id: http_login

- alias: "HASS: IP Banned [notify to group system]"
  id: ba2318c5-5c2e-4575-aa13-02f53063793d
  mode: queued
  max: 5
  trigger:
    - platform: state
      entity_id: persistent_notification.ip_ban
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tlg_group_system
        disable_web_page_preview: true
        message: |
          *Внимание!*
          Заблокирован IP: {{ state_attr('persistent_notification.ip_ban', 'message').split('Too many login attempts from ')[1] }}
          _http://whatismyipaddress.com/ip/{{ state_attr('persistent_notification.ip_ban', 'message').split('Too many login attempts from ')[1] }}_
    - service: persistent_notification.dismiss
      data:
        notification_id: ip_ban
```

and spook creates a problem for each such entity, which doesn't seem right to me =)

![image](https://user-images.githubusercontent.com/32452033/225222815-b710f6f5-f8f1-4596-a014-193ea4b735fd.png)

The persistent_notification.* entities are really not there at the time of the check, but they appear and disappear as they work.
