### ISSUE TITLE
False possitive "unknown entity"

### ISSUE THREAD

**Issue by to4ko** [frenck/spook#71]
False possitive unknown entity

![image](https://user-images.githubusercontent.com/45161980/225421323-fff87ee0-be84-41f9-9a17-8cede6a160fc.png)

Both switches is available and online
![image](https://user-images.githubusercontent.com/45161980/225421768-47563a15-7102-47d4-ac0c-c0d123435124.png)

**Comment by to4ko** [comment]
initial code

```yaml
      - service: switch.turn_on
        data:
          entity_id: switch.0x54ef441000680083_channel_2, switch.0x54ef441000680083_channel_1
```

once changed to - message dissapeared
```yaml
      - service: switch.turn_on
        entity_id: switch.0x54ef441000680083_channel_2,switch.0x54ef441000680083_channel_1
```
