### ISSUE TITLE
light group causes "Unknown entities used in <automation>"

### ISSUE THREAD

**Issue by tinuva** [frenck/spook#773]
### What version of Spook are you using?

3.0.1

### What version of Home Assistant are you using?

2024.5.5

### The problem

Spook reports an issue that I have unknown entities.

Error:
![Screenshot 2024-06-01 at 17 10 58](https://github.com/frenck/spook/assets/5417682/e99a0273-44ae-40e3-95a9-f5b6f1d128c8)

However these do exist according to developer tools:
![Screenshot 2024-06-01 at 17 11 27](https://github.com/frenck/spook/assets/5417682/b369c5c0-9ba5-40d2-863d-e89aeb6691b8)

I have them configured like so in a yaml file:
```yaml
light:
  - platform: group
    unique_id: lights_while_awake
    name: Lights while awake
    entities:
      - light.courtyard_braai
  - platform: group
    name: Lights while awake with guests
    unique_id: lights_while_awake_with_guests
    entities:
      - light.courtyard_lounge
      - light.courtyard_main_bedroom
      - light.outside_scullery
      - light.outside_main_bathroom
      - light.pool
```

Is there something wrong with my configuration?
Or is there another reason I can't convince spook that these really do exist?
