### ISSUE TITLE
Valid action in script is reported as unknown for an automation which uses that script

### ISSUE THREAD

**Issue by Vitani** [frenck/spook#858]
### What version of Spook are you using?

3.1.0

### What version of Home Assistant are you using?

2024.11.1 (it was also present in 2024.10.x)

### The problem

I get this error:

> The automation "🔥 Turn on Kettle" (`automation.claire_near_home`) has an unknown action: `water_heater.set_temperature`.

I see two issues with this spook:

1. The action `water_heater.set_temperature` shouldn't be _unknown_, it is a [valid action](https://www.home-assistant.io/integrations/water_heater/#water-heater-control-actions)
2. This automation **doesn't** use the `water_heater.set_temperature` action, however it **does** call a script which contains this action.

Automation YAML (`automation.claire_near_home`):

```yaml
alias: 🔥 Turn on Kettle
description: ""
mode: single
triggers:
  - entity_id: person.claire
    zone: zone.near_home
    event: enter
    id: near_home
    trigger: zone
  - type: opened
    device_id: 577747254dfd42d9a9e9ce289f6e36dd
    entity_id: binary_sensor.master_bedroom_door_contact
    domain: binary_sensor
    id: first_coffee
    trigger: device
  - entity_id:
      - sensor.claire_s_s24_ultra_charger_type
    id: first_coffee
    to: none
    trigger: state
conditions:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: near_home
          - condition: time
            after: "07:30:00"
            before: "19:00:00"
      - condition: and
        conditions:
          - condition: trigger
            id: first_coffee
          - condition: time
            before: "09:00:00"
            after: "07:00:00"
          - type: is_open
            condition: device
            device_id: 577747254dfd42d9a9e9ce289f6e36dd
            entity_id: binary_sensor.master_bedroom_door_contact
            domain: binary_sensor
          - condition: zone
            entity_id: person.claire
            zone: zone.home
          - condition: state
            entity_id: switch.kitchen_kettle
            state: "off"
            for:
              hours: 2
              minutes: 0
              seconds: 0
          - condition: state
            entity_id: sensor.claire_s_s24_ultra_charger_type
            state: none
actions:
  - data: {}
    action: script.turn_kettle_on
```

Script YAML (`script.turn_kettle_on`)

```yaml
alias: Kettle On
sequence:
  - alias: Set Temp based on time of day
    if:
      - condition: time
        after: "00:00:00"
        before: "12:00:00"
    then:
      - metadata: {}
        data:
          temperature: 90
        target:
          entity_id: water_heater.kitchen_kettle
        action: water_heater.set_temperature
      - metadata: {}
        data: {}
        target:
          entity_id: switch.kitchen_kettle_keep_warm
        action: switch.turn_on
    else:
      - metadata: {}
        data:
          temperature: 100
        target:
          entity_id: water_heater.kitchen_kettle
        action: water_heater.set_temperature
  - metadata: {}
    data: {}
    target:
      entity_id: switch.kitchen_kettle
    action: switch.turn_on
mode: restart
icon: mdi:kettle-steam
```
