### ISSUE TITLE
Missing repair for unknown entity. Blueprint > Script > Trigger Input

### ISSUE THREAD

**Issue by jlpouffier** [frenck/spook#865]
### What version of Spook are you using?

3.1.0

### What version of Home Assistant are you using?

2024.11.2

### The problem

I recently renamed/deleted/recreated a bunch of new entities and used Spook as my ally to tell me where they were used.

Here is a case that it missed.

#### Context
I have a blueprint ([That one](https://github.com/jlpouffier/home-assistant-config/blob/master/blueprints/script/jlo/power_notification_creator.yaml)) that creates scripts for my notification.
I have a `trigger` `input` on the blueprint to let the user define when they want the notification to be discarded called `discard_when`.
This `input` is then used in a `wait_for_trigger` on the script.

Here is a full config of this blueprint for one case (Notify me when the windows are open and it's raining - As long as it's rating and the windows are open - Two `trigger` on `discard_when`)

```yaml
use_blueprint:
  path: jlo/power_notification_creator.yaml
  input:
    target: send_to_persons_in_zones
    zones:
      - zone.home
    default_title: 🌂 In pleut!
    default_message: Certaines portes sont ouvertes et il commence a pleuvoir
    discard_when:
      - trigger: state
        entity_id:
          - binary_sensor.all_doors
        to: "off"
      - trigger: state
        entity_id:
          - binary_sensor.is_raining_now
        to: "off"
    default_tag: rain_doors_open
```

#### Problem

I recently removed my binary sensor `binary_sensor.is_raining_now` but spook missed that particular case
![CleanShot 2024-11-20 at 11 58 13](https://github.com/user-attachments/assets/24f10d22-31df-435a-93d5-82dad57b7f6c)
