### ISSUE TITLE
Missing repair for unknown entity. Heading Card > Entities & Heading Card > Entities > Visibility

### ISSUE THREAD

**Issue by jlpouffier** [frenck/spook#866]
### What version of Spook are you using?

3.1.0

### What version of Home Assistant are you using?

2024.11.2

### The problem

I recently renamed/deleted/recreated a bunch of new entities and used Spook as my ally to tell me where they were used.

Here is a case that it missed.

**⚠️ In all the below cases,  `binary_sensor.is_raining_now` is not present in my system. It's a former entity that I deleted**

#### Case 1: Heading Card > Entities
An unknown entity on a `heading` card does not raise a repair
![CleanShot 2024-11-20 at 12 04 10](https://github.com/user-attachments/assets/6558e8b3-9750-46de-bac6-763801f66aaa)

Card config
```yaml
type: heading
heading: Heading card
heading_style: title
badges:
  - type: entity
    entity: binary_sensor.is_raining_now
```

#### Case 2: Heading Card > Entities > Visibility
An unknown entity on a visibility option of an entity on a `heading` card does not raise a repair

Card config
```yaml
type: heading
heading: Heading card
heading_style: title
badges:
  - type: entity
    show_state: true
    show_icon: true
    entity: zone.home
    visibility:
      - condition: state
        entity: binary_sensor.is_raining_now
        state: "on"
```

#### Additional note.
Writting this issue, I tested a bit more the `visibility` option.
And I think spook misses unknown entities in the visibility option regardless of the level (Section, Card, or entity in card)

Here is an example
```yaml
type: grid
cards:
  - type: heading
    heading: Heading card
    heading_style: title
    badges:
      - type: entity
        show_state: true
        show_icon: true
        entity: zone.home
        visibility:
          - condition: state
            entity: binary_sensor.is_raining_now
            state: "on"
  - type: tile
    entity: zone.home
    visibility:
      - condition: state
        entity: binary_sensor.is_raining_now
        state: "on"
visibility:
  - condition: state
    entity: binary_sensor.is_raining_now
    state: "on"

```
