### ISSUE TITLE
False alarm (or new user error)

### ISSUE THREAD

**Issue by DarrenPIngram** [frenck/spook#963]
### What version of Spook are you using?

latest as installed on May 1

### What version of Home Assistant are you using?

Core 2025.4.4 Supervisor 2025.04.1 Operating System 15.2 Frontend 20250411.0

### The problem

On a brand new installation and before I got to read what to do I got an alert in "notifications" telling me error entries in a dashboard! Excellent.

```
Spook has found a ghost in your dashboards 👻

While floating around, Spook crossed path with the following dashboard:

[Upper Floor](http://192.168.0.4:8123/upper-floor/0?edit=1)

This dashboard references the following entities, which are unknown to Home Assistant:

sensor.upperfloor_powerplug_trappan_1
sensor.upperfloor_powerplug_trappan_2
sensor.upperfloor_powerplug_trappan_3
To fix this error, [edit the dashboard](http://192.168.0.4:8123/upper-floor/0?edit=1) and remove the use of these non-existing entities.
```

But when I go to the dashboard there is no such references.

There are three entries like this

```
:
                  - type: vertical-stack
                    cards:
                      - type: custom:mushroom-entity-card
                        entity: switch.upperfloor_powerplug_trappan_l1
                        name: Powerstrip-1
                        icon: mdi:power-plug
                        tap_action:
                          action: toggle
```

So might Spook be missing the _l1 (and _l2 and _l3 ) and getting confused?

Else where in blazes is this report hiding as it is not showing up in the yaml for that dashboard!

### Anything in the logs? Paste it here!

```plain text

```
